<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPINHYDW00B1" ignored="0" name="RestAssuredTest" tests="9" failures="4" timestamp="2020-02-26T19:47:56 IST" time="38.97" errors="0">
  <testcase name="verifyHttpStatusCode" time="1.517" classname="restAssured.RestAssured.TestingRestServices"/>
  <testcase name="verifyHttpStatusCode" time="1.742" classname="restAssured.RestAssured.TestingRestServices"/>
  <testcase name="verifyHttpResponseBody" time="0.011" classname="restAssured.RestAssured.TestingRestServices">
    <failure type="java.util.ConcurrentModificationException">
      <![CDATA[java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at java_util_Iterator$next$0.call(Unknown Source)
at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:70)
at io.restassured.filter.FilterContext$next.call(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1631)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1637)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:166)
at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
at restAssured.RestAssured.TestingRestServices.verifyHttpResponseBody(TestingRestServices.java:91)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifyHttpResponseBody -->
  <testcase name="VerifyPresenseOfHeadersInHttpResponse" time="0.811" classname="restAssured.RestAssured.TestingRestServices">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at restAssured.RestAssured.TestingRestServices.VerifyPresenseOfHeadersInHttpResponse(TestingRestServices.java:53)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPresenseOfHeadersInHttpResponse -->
  <testcase name="VerifyPresenseOfHeadersInHttpResponse" time="1.228" classname="restAssured.RestAssured.TestingRestServices"/>
  <testcase name="verifyHttpResponseHeader" time="0.0" classname="restAssured.RestAssured.TestingRestServices">
    <skipped/>
  </testcase> <!-- verifyHttpResponseHeader -->
  <testcase name="verifyResponseStatusCodeForPost" time="34.132" classname="restAssured.RestAssured.TestingRestServices">
    <failure type="java.lang.AssertionError" message="expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [200]
at restAssured.RestAssured.TestingRestServices.verifyResponseStatusCodeForPost(TestingRestServices.java:113)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyResponseStatusCodeForPost -->
  <testcase name="verifyResponseStatusCodeForPost" time="1.181" classname="restAssured.RestAssured.TestingRestServices">
    <failure type="java.lang.AssertionError" message="expected [201] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [405]
at restAssured.RestAssured.TestingRestServices.verifyResponseStatusCodeForPost(TestingRestServices.java:113)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyResponseStatusCodeForPost -->
  <testcase name="verifyHttpResponseBodyForPost" time="0.0" classname="restAssured.RestAssured.TestingRestServices">
    <skipped/>
  </testcase> <!-- verifyHttpResponseBodyForPost -->
</testsuite> <!-- RestAssuredTest -->
